DROP TABLE `member_info`;
DROP TABLE `board_info`;
DROP TABLE `board_type_info`;
DROP TABLE `comment_info`;

CREATE TABLE `member_info` (
	`id`	INT	NOT NULL AUTO_INCREMENT,
	`email`	VARCHAR(255)	NOT NULL,
	`password`	VARCHAR(255)	NOT NULL,
	`name`	VARCHAR(255)	NOT NULL,
	`created_at`	DATETIME	DEFAULT CURRENT_TIMESTAMP,
	`updated_at`	DATETIME	DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `board_info` (
	`id`	INT	NOT NULL AUTO_INCREMENT,
	`member_id`	INT	NOT NULL,
	`board_type_id`	INT	NOT NULL,
	`subject`	TEXT	NOT NULL,
	`content`	MEDIUMTEXT	NOT NULL,
	`hits`	INT	DEFAULT 0,
	`recommend`	INT	DEFAULT 0,
	`created_at`	DATETIME	DEFAULT CURRENT_TIMESTAMP,
	`updated_at`	DATETIME	DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `board_type_info` (
	`id`	INT	NOT NULL AUTO_INCREMENT,
	`name`	VARCHAR(255)	NOT NULL,
	`created_at`	DATETIME	DEFAULT CURRENT_TIMESTAMP,
	`updated_at`	DATETIME	DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `comment_info` (
	`id`	INT	NOT NULL AUTO_INCREMENT,
	`board_id`	INT	NOT NULL,
	`member_id`	INT	NOT NULL,
	`content`	MEDIUMTEXT	NOT NULL,
	`created_at`	DATETIME	DEFAULT CURRENT_TIMESTAMP,
	`updated_at`	DATETIME	DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
